"use client"
import { useEffect, useState } from "react"
import { intelligenceFetch } from "@/lib/intelligence/client"
type Topic = { tag: string; mentions: number; customers: number; this_week: number; last_week: number; intent_customers: number; quotes: string[]; evidence_keys: string[] }
type Insight = { surface_question: string; root_problem: string; desired_outcome: string; emotions: string[]; objections: string[]; buying_stage: string; related_products: string[]; themes: string[]; customer_language: { event_key: string; quote: string }[] }
type Customer = { customer_key: string; label: string; messages: number; incoming: number; last_at: string }
type Idea = { id: string; format: string; title: string; outline: string }
type Dashboard = { summary: { messages: number; customers: number; customer_messages: number; automation: number; automation_suspected: number; system: number; unknown: number }; topics: Topic[]; exact_words: { text: string; customers: number; mentions: number; evidence_key: string }[]; customers: Customer[]; insights: { customer_key: string; period: string; insight: Insight }[]; ai: { ready: number; pending: number; errors: number }; revenue: { currency: string; amount: number; purchases: number }[]; clicks: number; attributed_purchases: number; purchase_tracking_connected: boolean; products: { product_key: string; label: string; keywords: string[] }[] }
type Journey = { messages: { event_key: string; occurred_at: string; direction: string; text: string; kind: string; source: string; attachments: unknown[] }[]; more: boolean; insights: { period: string; insight: Insight }[]; purchases: { order_key: string; paid_at: string; currency: string; amount: number; source: string }[] }
const formats = ["Reel", "Carousel", "Story", "FAQ", "Sales Page", "Content Idea"]
const btn = "rounded-lg border px-3 py-2 text-sm disabled:opacity-50"
const field = "rounded-lg border bg-background p-2 text-sm"
const labels: Record<string, string> = { customer: "고객 원문", automation: "자동 DM 확인", automation_suspected: "자동 DM 추정", manual: "직접 발송 확인", outgoing_unknown: "내 답변 · 발송 방식 미확인", system: "시스템 기록", unknown: "발신 방향 미확인" }
function InsightView({ value }: { value: Insight }) {
  return <div className="space-y-2"><p><b>표면 질문:</b> {value.surface_question || "근거 부족"}</p><p><b>실제 문제:</b> {value.root_problem || "근거 부족"}</p><p><b>원하는 변화:</b> {value.desired_outcome || "근거 부족"}</p><p><b>감정:</b> {value.emotions.join(" · ")}</p><p><b>구매장벽:</b> {value.objections.join(" · ")}</p><p><b>구매 단계:</b> {value.buying_stage} <span className="text-xs text-muted-foreground">(DM 해석 · 실제 결제와 별도)</span></p><p><b>관련 상품:</b> {value.related_products.join(" · ")}</p><p><b>주제:</b> {value.themes.join(" · ")}</p><div><b>고객이 실제로 쓴 표현</b>{value.customer_language.map(e => <blockquote key={e.event_key + e.quote} className="my-2 border-l-2 pl-3 whitespace-pre-wrap">{e.quote}</blockquote>)}</div></div>
}
export default function IntelligencePage() {
  const [data, setData] = useState<Dashboard | null>(null), [product, setProduct] = useState(""), [revision, setRevision] = useState(0)
  const [customer, setCustomer] = useState(""), [journey, setJourney] = useState<Journey | null>(null), [page, setPage] = useState(0)
  const [ideas, setIdeas] = useState<Idea[]>([]), [edit, setEdit] = useState<Idea | null>(null), [destination, setDestination] = useState("")
  const [error, setError] = useState(""), [status, setStatus] = useState(""), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true)
  const [settings, setSettings] = useState({ analysis_enabled: true, daily_limit: 5 })
  const [integration, setIntegration] = useState<{endpoint:string;secret:string;instructions:string} | null>(null)
  const [backfill, setBackfill] = useState<{status:string;conversations_done:number;messages_inserted:number;last_error:string|null} | null>(null)
  const [learning, setLearning] = useState<{id:string;title:string;format:string;requests:number;orders:number;paid_clicks:number;request_purchase_rate:number|null;revenue:{currency:string;amount:number}[]}[]>([])
  const [newProduct, setNewProduct] = useState({product_key:"",label:"",keywords:""})
  const [mergeId, setMergeId] = useState("")
  const [purchase, setPurchase] = useState({ order_key: "", amount: "", currency: "KRW", paid_at: "", confirmed: false })
  useEffect(() => {
    let active = true; setLoading(true); setError("")
    Promise.all([intelligenceFetch(`/api/intelligence?product=${encodeURIComponent(product)}`), intelligenceFetch("/api/intelligence?action=content"), intelligenceFetch("/api/intelligence?action=settings"), intelligenceFetch("/api/intelligence?action=backfill"), intelligenceFetch("/api/intelligence?action=learning")]).then(([d,c,s,b,l]) => { if (active) { setData(d); setIdeas(c.ideas); setSettings(s.settings); setBackfill(b.backfill); setLearning(l.learning) } }).catch(e => { if (active) setError(e.message) }).finally(() => { if (active) setLoading(false) })
    return () => { active = false }
  }, [product, revision])
  useEffect(() => {
    if (!customer) { setJourney(null); return }
    let active = true; setJourney(null)
    intelligenceFetch(`/api/intelligence?action=customer&key=${encodeURIComponent(customer)}&offset=${page * 100}`).then(j => { if (active) setJourney(j) }).catch(e => { if (active) setError(e.message) })
    return () => { active = false }
  }, [customer, page, revision])
  async function action(name: string, body: unknown) {
    setBusy(true); setError(""); setStatus("")
    try { const result = await intelligenceFetch(`/api/intelligence?action=${name}`, body); setStatus(result.url ? `추적 링크: ${result.url}` : result.status === "idle" ? "오늘 분석 한도에 도달했거나 분석 대기가 없어요." : result.status === "error" ? "AI 응답을 검증하지 못해 자동 재시도 대기로 남겼어요." : "저장됐어요."); setRevision(v => v + 1); return result } catch(e) { setError(e instanceof Error ? e.message : "처리하지 못했어요.") } finally { setBusy(false) }
  }
  const actions = (event_key: string) => <div className="flex flex-wrap gap-2">{formats.map(format => <button type="button" className={btn} key={format} disabled={busy} onClick={() => void action("content", { event_key, format })}>{format === "Content Idea" ? "소재로 저장" : `${format} 초안`}</button>)}</div>
  return <div className="mx-auto max-w-6xl space-y-6 p-6">
    <div><h1 className="text-3xl font-semibold">Customer Intelligence</h1><p className="mt-2 text-muted-foreground">고객 → 문제 → 욕구 → 장벽 → 행동 → 구매. 고객 원문과 AI 해석을 따로 보관합니다.</p></div>
    <div className="flex flex-wrap items-center gap-3"><label>상품 필터 <select className={field} value={product} onChange={e=>setProduct(e.target.value)}><option value="">모든 상품</option>{data?.products.map(p=><option key={p.product_key} value={p.product_key}>{p.label}</option>)}</select></label><button className={btn} disabled={busy || loading} onClick={()=>setRevision(v=>v+1)}>새로고침</button></div>
    {error && <p role="alert" className="text-destructive">{error}</p>}{status && <p role="status" className="break-all">{status}</p>}{loading && <p role="status">고객 데이터 집계 중…</p>}
    {data && <>
      <section className="grid grid-cols-2 gap-3 md:grid-cols-4">{[["통합 메시지",data.summary.messages],["대화 그룹",data.summary.customers],["고객 메시지",data.summary.customer_messages],["AI 분석 그룹",data.ai.ready]].map(([label,value])=><div className="rounded-xl border p-4" key={label}><p className="text-sm text-muted-foreground">{label}</p><p className="text-2xl font-semibold">{Number(value).toLocaleString()}</p></div>)}</section>
      <p className="text-sm text-muted-foreground">자동 발송 확인 {data.summary.automation} · 자동 발송 추정 {data.summary.automation_suspected} · 시스템 기록 {data.summary.system} · 방향 미확인 {data.summary.unknown}. 내 발신과 시스템 기록은 고객 고민 집계에서 제외합니다. 아직 연결되지 않은 내보내기 대화와 API 대화는 별도 그룹으로 유지합니다.</p>
      <section className="space-y-4 rounded-xl border p-5"><h2 className="text-xl font-semibold">반복 질문 · 실행을 막는 것 · 콘텐츠 기회</h2><p className="text-sm text-muted-foreground">전체 고객 원문에서 키워드로 찾은 신호입니다. 빈도와 구매 의도 표현으로 우선순위를 정합니다. 의미 해석은 아래 AI Insight와 구분됩니다.</p>
        <div className="grid gap-4 md:grid-cols-2">{data.topics.map(t=><article key={t.tag} className="space-y-3 rounded-lg bg-muted p-4"><h3 className="font-semibold">{t.tag}</h3><p className="text-sm">고객 {t.customers}명 · 언급 {t.mentions}회 · 구매 의도 표현 고객 {t.intent_customers}명</p><p className="text-sm">최근 7일 {t.this_week}회 · 이전 7일 {t.last_week}회 {t.last_week>0 ? `(${Math.round((t.this_week-t.last_week)/t.last_week*100)}%)` : "(비교 기준 부족)"}</p><blockquote className="whitespace-pre-wrap border-l-2 pl-3">{t.quotes[0]}</blockquote>{t.evidence_keys[0] && actions(t.evidence_keys[0])}</article>)}</div>
      </section>
      <details className="rounded-xl border p-5"><summary className="cursor-pointer">상품 필터 추가·수정</summary><div className="mt-3 grid gap-2 md:grid-cols-3"><input aria-label="상품 키" className={field} placeholder="영문 키 (예: new-course)" value={newProduct.product_key} onChange={e=>setNewProduct(p=>({...p,product_key:e.target.value}))}/><input aria-label="상품 이름" className={field} placeholder="상품 이름" value={newProduct.label} onChange={e=>setNewProduct(p=>({...p,label:e.target.value}))}/><input aria-label="상품 키워드" className={field} placeholder="키워드, 쉼표로 구분" value={newProduct.keywords} onChange={e=>setNewProduct(p=>({...p,keywords:e.target.value}))}/><button className={btn} disabled={busy} onClick={()=>void action("product",{...newProduct,keywords:newProduct.keywords.split(",").map(s=>s.trim()).filter(Boolean)})}>상품 필터 저장</button></div><p className="mt-2 text-xs">같은 상품 키로 저장하면 수정됩니다. 상품은 고객 분석의 필터입니다.</p></details>
      <section className="space-y-4 rounded-xl border p-5"><h2 className="text-xl font-semibold">Their Exact Words</h2>{data.exact_words.map(w=><article key={w.evidence_key} className="space-y-2 border-b pb-3"><blockquote className="whitespace-pre-wrap">{w.text}</blockquote><p className="text-xs text-muted-foreground">서로 다른 고객 {w.customers}명 · {w.mentions}회</p>{actions(w.evidence_key)}</article>)}</section>
      <section className="space-y-4 rounded-xl border p-5"><h2 className="text-xl font-semibold">AI Insight</h2><p className="text-sm">분석 완료 {data.ai.ready}그룹 · 대기 {data.ai.pending} · 재시도 대기 {data.ai.errors}. 월별 고객 대화에서 필요한 원문 일부만 분석합니다.</p><div className="flex flex-wrap items-center gap-3"><label><input type="checkbox" checked={settings.analysis_enabled} onChange={e=>setSettings(s=>({...s,analysis_enabled:e.target.checked}))}/> 자동 분석</label><label>하루 최대 <input aria-label="하루 분석 횟수" className={`${field} w-20`} type="number" min={0} max={20} value={settings.daily_limit} onChange={e=>setSettings(s=>({...s,daily_limit:Number(e.target.value)}))}/>그룹</label><button className={btn} disabled={busy} onClick={()=>void action("settings",settings)}>분석 설정 저장</button><button className={btn} disabled={busy} onClick={()=>void action("analyze",{})}>대기 분석 1개 처리</button></div>
        {data.insights.length===0 && <p>아직 검증된 AI 분석이 없어요. 자동 분석은 시간별로 진행되며 하루 한도를 지킵니다.</p>}{data.insights.map(i=><article key={i.customer_key+i.period} className="space-y-3 rounded-lg bg-muted p-4"><p className="text-xs text-muted-foreground">{i.period} · AI 해석</p><InsightView value={i.insight}/><button className={btn} onClick={()=>{setPage(0);setCustomer(i.customer_key)}}>고객의 원문·여정 보기</button>{i.insight.customer_language[0] && actions(i.insight.customer_language[0].event_key)}</article>)}
      </section>
      <section className="space-y-3 rounded-xl border p-5"><h2 className="text-xl font-semibold">최근 DM API backfill</h2><p className="text-sm">Meta가 실제로 반환하는 범위만 가져옵니다. 과거 ZIP과 겹치는 Meta 메시지 ID는 중복으로 저장하지 않습니다. 새로운 DM은 기존 webhook으로 수집합니다.</p><p>{backfill ? `상태: ${backfill.status} · 대화 ${backfill.conversations_done}개 처리 · 신규 메시지 ${backfill.messages_inserted}개` : "아직 시작되지 않았어요."}</p>{backfill?.last_error && <p className="text-destructive">{backfill.last_error}</p>}<button className={btn} disabled={busy} onClick={()=>void action("backfill",{})}>API 동기화 한 단계 실행</button></section>
      <section className="space-y-4 rounded-xl border p-5"><h2 className="text-xl font-semibold">Customer Journey</h2><label className="block">고객 대화 <select className={`${field} mt-2 w-full`} value={customer} onChange={e=>{setPage(0);setCustomer(e.target.value)}}><option value="">최근 대화 선택</option>{data.customers.map(c=><option key={c.customer_key} value={c.customer_key}>{c.label} · {c.messages}개 메시지</option>)}</select></label>
        {customer && !journey && <p>여정 불러오는 중…</p>}{journey && <><div className="max-h-[600px] space-y-3 overflow-auto">{journey.messages.map(m=><article key={m.event_key} className="rounded-lg bg-muted p-3"><p className="text-xs text-muted-foreground">{new Date(m.occurred_at).toLocaleString("ko-KR")} · {labels[m.kind] || m.kind} · {m.source}</p><p className="whitespace-pre-wrap break-words">{m.text || "[첨부 정보 또는 시스템 이벤트]"}</p>{m.attachments?.length>0 && <p className="text-xs">첨부 정보 {m.attachments.length}개</p>}</article>)}</div><div className="flex gap-2"><button className={btn} disabled={page===0} onClick={()=>setPage(p=>p-1)}>이전 100개</button><button className={btn} disabled={!journey.more} onClick={()=>setPage(p=>p+1)}>다음 100개</button></div>{journey.insights.map(i=><div key={i.period} className="rounded-lg border p-3"><h3>{i.period} AI Insight</h3>{i.insight && <InsightView value={i.insight}/>}</div>)}{journey.purchases.map(p=><p key={p.order_key}>확인된 구매: {new Date(p.paid_at).toLocaleDateString()} · {p.currency} {Number(p.amount).toLocaleString()} · {p.source}</p>)}</>}
        {customer.startsWith("export:") && <details><summary className="cursor-pointer">확인된 동일 고객의 현재 Inbox와 연결</summary><p className="text-xs text-muted-foreground">이름만 같다고 자동으로 합치지 않습니다. 같은 고객임을 확인한 Inbox의 conversation ID를 입력하세요.</p><input aria-label="현재 Inbox 대화 ID" className={field} value={mergeId} onChange={e=>setMergeId(e.target.value)}/><button className={btn} disabled={busy || !mergeId} onClick={()=>void action("merge",{thread_key:customer.slice(7),conversation_id:mergeId})}>동일 고객으로 연결</button></details>}
      </section>
      <section className="space-y-4 rounded-xl border p-5"><h2 className="text-xl font-semibold">Conversion Learning</h2><p>추적 링크 요청 {data.clicks}회 · 클릭 ID에 연결된 주문 {data.attributed_purchases}건</p><p className="text-sm text-muted-foreground">링크 요청에는 미리보기 봇과 반복 클릭이 포함될 수 있어요. 고유 방문자 수로 보지 않습니다. 클릭 ID가 결제에 전달된 주문만 콘텐츠에 연결합니다.</p>{!data.purchase_tracking_connected && <p>결제 데이터 미연결 — 구매전환율·매출 성과는 아직 판단하지 않습니다.</p>}{data.revenue.map(r=><p key={r.currency}>확인된 주문 {r.purchases}건 · {r.currency} {Number(r.amount).toLocaleString()}</p>)}
        <button className={btn} disabled={busy} onClick={()=>{setError(""); intelligenceFetch("/api/intelligence?action=integration").then(setIntegration).catch(e=>setError(e.message))}}>WooCommerce 자동 결제 연동 설정 보기</button>{integration && <div className="space-y-2 rounded-lg bg-muted p-3"><p className="break-all">Webhook URL: {integration.endpoint}</p><p className="break-all">Webhook Secret: {integration.secret}</p><p className="text-sm">{integration.instructions}</p><p className="text-sm">WordPress 플러그인 설치와 WooCommerce 웹훅 등록 후 실제 결제 테스트가 필요합니다.</p></div>}
        {learning.map(l=><article key={l.id} className="rounded-lg border p-3"><p className="font-semibold">{l.format} · {l.title}</p><p>링크 요청 {l.requests}회 · 결제로 이어진 클릭 {l.paid_clicks}회 · 주문 {l.orders}건</p>{l.request_purchase_rate!==null && <p className="text-xs">링크 요청 대비 결제 연결 {l.request_purchase_rate}% (고유 고객 전환율과 다릅니다)</p>}{l.revenue.map(r=><p key={r.currency}>{r.currency} {Number(r.amount).toLocaleString()}</p>)}</article>)}
        {customer && <details><summary className="cursor-pointer">이 고객의 확인된 구매 기록 추가</summary><div className="mt-3 grid gap-2 md:grid-cols-2"><input aria-label="주문번호" className={field} placeholder="주문번호" value={purchase.order_key} onChange={e=>setPurchase(p=>({...p,order_key:e.target.value}))}/><input aria-label="결제 금액" className={field} placeholder="결제 금액" value={purchase.amount} onChange={e=>setPurchase(p=>({...p,amount:e.target.value}))}/><input aria-label="통화" className={field} value={purchase.currency} onChange={e=>setPurchase(p=>({...p,currency:e.target.value.toUpperCase()}))}/><input aria-label="결제 날짜" className={field} type="datetime-local" value={purchase.paid_at} onChange={e=>setPurchase(p=>({...p,paid_at:e.target.value}))}/><label><input type="checkbox" checked={purchase.confirmed} onChange={e=>setPurchase(p=>({...p,confirmed:e.target.checked}))}/> 실제 결제를 확인했습니다</label><button className={btn} disabled={busy || !purchase.confirmed} onClick={()=>void action("purchase",{...purchase,customer_key:customer})}>확인된 구매 저장</button></div></details>}
      </section>
      <section className="space-y-4 rounded-xl border p-5"><h2 className="text-xl font-semibold">저장된 콘텐츠 초안</h2><p className="text-sm text-muted-foreground">고객 원문에 연결된 편집 가능한 초안입니다. 실제 콘텐츠 제작과 게시 전 검토가 필요합니다.</p>{ideas.map(i=><button key={i.id} className="block w-full rounded-lg border p-3 text-left" onClick={()=>setEdit({...i})}>{i.format} · {i.title}</button>)}{edit && <div className="space-y-3"><input aria-label="초안 제목" className={`${field} w-full`} value={edit.title} onChange={e=>setEdit(i=>i?{...i,title:e.target.value}:i)}/><textarea aria-label="콘텐츠 초안" className={`${field} w-full`} rows={10} value={edit.outline} onChange={e=>setEdit(i=>i?{...i,outline:e.target.value}:i)}/><button className={btn} disabled={busy} onClick={()=>void action("edit-content",edit)}>초안 저장</button><div className="flex flex-wrap gap-2"><input aria-label="구매 페이지 URL" className={`${field} flex-1`} placeholder="https:// 구매 페이지 URL" value={destination} onChange={e=>setDestination(e.target.value)}/><button className={btn} disabled={busy || !destination} onClick={()=>void action("link",{content_id:edit.id,destination,customer_key:customer || null})}>콘텐츠 추적 링크 만들기</button></div></div>}</section>
    </>}
  </div>
}
