"use client"
import { useEffect, useState } from "react"
import { ArrowRight, Sparkles } from "lucide-react"
import { intelligenceFetch } from "@/lib/intelligence/client"
import { IntelligenceManagement } from "./management"

type Evidence={event_key:string;customer_key:string;text:string;quality_kind:string;occurred_at:string}
type Topic={tag:string;title:string;next_action:string;mentions:number;conversations:number;this_week:number;last_week:number;intent_conversations:number;orders:number;examples:Evidence[]}
type Insight={surface_question:string;root_problem:string;desired_outcome:string;objections:string[];customer_language:{event_key:string;quote:string}[]}
type Dashboard={summary:{raw:number;incoming:number;excluded:number;unclear:number;signals:number;conversations:number;unmapped:number};categories:{quality_kind:string;messages:number}[];topics:Topic[];examples:Evidence[];products:{product_key:string;label:string}[];ai:{ready:number;pending:number};insights:{customer_key:string;period:string;insight:Insight}[];purchase_tracking_connected:boolean}
const names:Record<string,string>={problem:'고민·실행 문제',desire:'원하는 결과',objection:'구매 망설임',question:'구매 전 질문',support:'사용·결제 지원',testimonial:'구체적 성과·후기',purchase_report:'구매했다고 언급',reaction:'반응·이모지',courtesy:'인사·감사',followup:'확인·연락 예고',trigger:'팔로우·트리거',keyword_only:'키워드만 보낸 요청',no_text:'본문 없는 기록',unclear:'맥락 부족·분류 보류'}
const btn='inline-flex items-center justify-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-medium hover:bg-muted disabled:opacity-50'
const field='ml-2 rounded-lg border bg-background p-2 text-sm'
const tabs=[['overview','우선 볼 것'],['words','고객 원문'],['content','콘텐츠 보관함'],['conversion','구매 성과'],['settings','설정']] as const
const count=(n:number)=>n.toLocaleString('ko-KR')

export default function IntelligenceOverview(){
 const [tab,setTab]=useState<string>('overview'),[days,setDays]=useState(30),[scope,setScope]=useState('marketing'),[product,setProduct]=useState(''),[revision,setRevision]=useState(0)
 const [data,setData]=useState<Dashboard|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false)
 const [topic,setTopic]=useState<string|null>(null),[customer,setCustomer]=useState<{key:string;anchor:string}|null>(null),[format,setFormat]=useState('Content Idea'),[showAll,setShowAll]=useState(false),[kind,setKind]=useState('')
 useEffect(()=>{let active=true;setLoading(true);setError('');setTopic(null);setKind('');setShowAll(false)
  intelligenceFetch(`/api/intelligence?days=${days}&scope=${scope}&product=${encodeURIComponent(product)}`).then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)})
  return()=>{active=false}
 },[days,scope,product,revision])
 const selected=data?.topics.find(t=>t.tag===topic)
 const examples=(selected?.examples||data?.examples||[]).filter(e=>!kind||e.quality_kind===kind)
 async function save(e:Evidence){setBusy(true);setError('');try{await intelligenceFetch('/api/intelligence?action=content',{event_key:e.event_key,format});setStatus(`${format} 소재를 보관함에 저장했어요. 원문이 함께 연결됩니다.`)}catch(e){setError(e instanceof Error?e.message:'저장하지 못했어요.')}finally{setBusy(false)}}
 function quote(e:Evidence){return <article key={e.event_key} className="space-y-4 rounded-2xl border bg-card p-5"><div className="flex justify-between gap-3 text-xs text-muted-foreground"><span className="rounded-full bg-muted px-3 py-1">{names[e.quality_kind]||'고객 원문'}</span><time>{new Date(e.occurred_at).toLocaleDateString('ko-KR')}</time></div><blockquote className="max-h-72 overflow-auto whitespace-pre-wrap break-words border-l-2 border-primary/50 pl-4 leading-relaxed">{e.text}</blockquote><div className="flex flex-wrap gap-2"><button className={btn} onClick={()=>setCustomer({key:e.customer_key,anchor:e.event_key})}>앞뒤 대화 보기</button><button className={btn} disabled={busy} onClick={()=>void save(e)}>콘텐츠 소재로 저장 <ArrowRight className="size-4"/></button></div></article>}
 return <div className="mx-auto max-w-6xl space-y-7 p-4 md:p-8">
  <header className="flex flex-wrap justify-between gap-4"><div><p className="mb-2 text-sm text-muted-foreground">Customer Intelligence</p><h1 className="text-2xl font-semibold md:text-3xl">고객의 말에서 다음 할 일을 찾으세요</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-muted-foreground">반복되는 고민과 구매장벽을 확인하고, 실제 고객 표현을 콘텐츠·FAQ·판매 페이지에 활용하세요.</p></div><button className={btn} disabled={loading} onClick={()=>setRevision(v=>v+1)}>새로고침</button></header>
  <nav aria-label="고객 분석 메뉴" className="flex gap-1 overflow-x-auto border-b">{tabs.map(([key,label])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>{setTab(key);setCustomer(null)}} className={`shrink-0 border-b-2 px-4 py-3 text-sm ${tab===key?'border-primary font-semibold':'border-transparent text-muted-foreground'}`}>{label}</button>)}</nav>
  {error&&<div role="alert" className="rounded-xl border border-destructive/30 p-4 text-sm text-destructive">{error}</div>}{status&&<div role="status" className="rounded-xl bg-muted p-4 text-sm">{status}<button className="ml-3 underline" onClick={()=>{setCustomer(null);setTab('content')}}>보관함 열기</button></div>}
  {customer?<section className="space-y-5"><button className={btn} onClick={()=>setCustomer(null)}>← 분석 화면으로 돌아가기</button><IntelligenceManagement key={customer.key+customer.anchor} mode="journey" initialCustomer={customer.key} initialEventKey={customer.anchor}/></section>:tab==='content'||tab==='conversion'||tab==='settings'?<IntelligenceManagement key={tab} mode={tab}/>:<>
   <div className="flex flex-wrap gap-3"><label className="text-sm">기간<select className={field} value={days} onChange={e=>setDays(Number(e.target.value))}>{[[7,'최근 7일'],[30,'최근 30일'],[90,'최근 90일'],[365,'최근 1년'],[0,'전체 기간']].map(([n,l])=><option key={n} value={n}>{l}</option>)}</select></label><label className="text-sm">대상<select className={field} value={scope} onChange={e=>setScope(e.target.value)}><option value="marketing">구매 전 고민·질문</option><option value="support">사용·결제 지원</option><option value="testimonial">구체적 성과·후기</option></select></label><label className="text-sm">상품<select className={field} value={product} onChange={e=>setProduct(e.target.value)}><option value="">모든 상품</option>{data?.products.map(p=><option key={p.product_key} value={p.product_key}>{p.label}</option>)}</select></label></div>
   {loading?<div role="status" className="animate-pulse rounded-2xl bg-muted p-8">의미 있는 고객 문의를 집계하고 있어요…</div>:data&&<>
    <div className="grid gap-3 sm:grid-cols-3">{[['분석할 문의',data.summary.signals,scope==='support'?'도움이 필요한 사용·결제 문의':scope==='testimonial'?'구체적 변화가 있는 후기':'의미 있는 질문·문제·욕구·장벽'],['관련 대화',data.summary.conversations,'같은 대화의 반복 메시지는 한 번 집계'],['제외한 잡음',data.summary.excluded,'반응·인사·확인·키워드 요청']].map(([label,n,hint])=><div key={label} className="rounded-2xl border p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="my-2 text-3xl font-semibold">{count(Number(n))}</p><p className="text-xs text-muted-foreground">{hint}</p></div>)}</div>
    {tab==='overview'?<>
     <section className="space-y-4"><h2 className="text-xl font-semibold">{scope==='marketing'?'먼저 다룰 주제 3개':scope==='support'?'지원 안내에서 개선할 것':'고객이 경험한 구체적 변화'}</h2><p className="text-sm text-muted-foreground">{data.purchase_tracking_connected?'실제 구매 연결 → 구매 의도 표현 → 관련 대화 수 순입니다.':'결제 데이터 미연결: 전환율·매출은 판단하지 않습니다. 구매 의도 표현과 관련 대화 수로 정렬합니다.'}</p>
      {!data.topics.length&&<p className="rounded-2xl border p-6">이 기간에 분류된 주제가 없어요. 기간을 넓히거나 아래 고객 원문을 확인하세요.</p>}
      <div className="grid gap-4 lg:grid-cols-3">{(showAll?data.topics:data.topics.slice(0,3)).map((t,i)=><article key={t.tag} className="flex flex-col gap-4 rounded-2xl border bg-card p-5"><span className="text-xs text-muted-foreground">주제 {i+1} · 문구 규칙으로 찾은 신호</span><h3 className="text-lg font-semibold leading-snug">{t.title}</h3><p className="text-sm">관련 대화 <b>{count(t.conversations)}개</b> · 구매 의도 표현 {count(t.intent_conversations)}개</p><p className="text-xs text-muted-foreground">최근 7일 {t.this_week}개 / 이전 7일 {t.last_week}개{t.last_week>=5?` · ${Math.round((t.this_week-t.last_week)/t.last_week*100)}%`:' · 추세 비교 표본 부족'}</p>{t.examples?.[0]&&<blockquote className="line-clamp-4 border-l-2 pl-3 text-sm leading-relaxed">{t.examples[0].text}</blockquote>}<div className="mt-auto space-y-3"><p className="rounded-xl bg-muted p-3 text-sm"><b>다음 행동</b><br/>{t.next_action}</p>{t.orders>0&&<p className="text-xs">언급 후 30일 내 구매 {t.orders}건 · 인과관계 증명과 별도</p>}<button className={`${btn} w-full`} onClick={()=>{setTopic(t.tag);setTab('words')}}>고객 원문 예시 보기 <ArrowRight className="size-4"/></button></div></article>)}</div>
      {data.topics.length>3&&<button className={btn} onClick={()=>setShowAll(v=>!v)}>{showAll?'중요한 3개만 보기':`다른 주제 ${data.topics.length-3}개 보기`}</button>}
     </section>
     <section className="space-y-4"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-semibold">고객이 실제로 쓴 말</h2><button className={btn} onClick={()=>{setTopic(null);setTab('words')}}>원문 더 보기</button></div><p className="text-sm text-muted-foreground">인사·감사·반응은 숨겼어요. 한 문장만 보고 판단하지 않도록 앞뒤 대화를 열 수 있습니다.</p><div className="grid gap-4 md:grid-cols-2">{data.examples.slice(0,4).map(quote)}</div></section>
     <details className="rounded-2xl border p-5"><summary className="cursor-pointer font-medium"><Sparkles className="mr-2 inline size-4"/>AI가 해석한 대화 {data.ai.ready}개</summary><p className="my-3 text-sm text-muted-foreground">새 기준을 통과한 대화만 분석합니다. 이전 기준의 결과는 숨겼으며, 원문과 AI 해석은 구분됩니다.</p>{!data.insights.length&&<p className="text-sm">정제된 분석 결과를 준비 중이에요. 위 주제·원문 집계는 지금 사용할 수 있습니다.</p>}{data.insights.map(i=><article key={i.customer_key+i.period} className="mt-4 space-y-3 rounded-xl bg-muted p-4"><p className="text-xs text-muted-foreground">{i.period} · AI 해석</p><h3 className="font-medium">{i.insight.surface_question||'고객이 표현한 문제'}</h3>{i.insight.root_problem&&<p className="text-sm">문제: {i.insight.root_problem}</p>}{i.insight.desired_outcome&&<p className="text-sm">원하는 결과: {i.insight.desired_outcome}</p>}{i.insight.objections?.length>0&&<p className="text-sm">장벽: {i.insight.objections.join(' · ')}</p>}{i.insight.customer_language.map(e=><blockquote key={e.event_key} className="border-l-2 pl-3 text-sm">{e.quote}</blockquote>)}<button className={btn} onClick={()=>setCustomer({key:i.customer_key,anchor:i.insight.customer_language[0]?.event_key||""})}>근거가 된 대화 보기</button></article>)}</details>
    </>:<section className="space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">{selected?.title||'분석 대상으로 남긴 고객 원문'}</h2><p className="mt-2 text-sm text-muted-foreground">{selected?'주제에 연결된 최근 예시 3개입니다.':'최근 원문 예시 24개입니다. 주제로 분류되지 않은 문의도 포함합니다.'} 원문은 수정하지 않습니다.</p></div>{selected&&<button className={btn} onClick={()=>setTopic(null)}>전체 원문 예시</button>}</div><div className="flex flex-wrap gap-3"><label className="text-sm">분류<select className={field} value={kind} onChange={e=>setKind(e.target.value)}><option value="">모든 분류</option>{['problem','desire','objection','question','support','testimonial'].map(k=><option key={k} value={k}>{names[k]}</option>)}</select></label><label className="text-sm">저장할 형식<select className={field} value={format} onChange={e=>setFormat(e.target.value)}>{['Reel','Carousel','Story','FAQ','Sales Page','Content Idea'].map(f=><option key={f}>{f}</option>)}</select></label></div><div className="grid gap-4 md:grid-cols-2">{examples.map(quote)}</div>{!examples.length&&<p className="rounded-xl bg-muted p-5">선택한 조건의 원문이 없습니다. 기간·분류를 바꿔보세요.</p>}</section>}
    <details className="rounded-2xl border p-5 text-sm"><summary className="cursor-pointer font-medium">무엇을 넣고 뺐나요?</summary><div className="mt-4 space-y-3"><p>고객 질문·실행 문제·욕구·구매장벽은 분석합니다. 사용 문의와 구체적 성과는 별도 대상으로 봅니다. 감사 뒤에 실제 질문이 있으면 남겨요.</p><p>맥락이 부족한 {count(data.summary.unclear)}건은 결론을 만들지 않고 보류합니다. 고객 발신 {count(data.summary.incoming)}건 중 선택한 분석 대상은 {count(data.summary.signals)}건입니다.</p><div className="grid gap-2 sm:grid-cols-2">{data.categories.map(c=><div className="flex justify-between rounded-lg bg-muted p-2" key={c.quality_kind}><span>{names[c.quality_kind]||c.quality_kind}</span><span>{count(c.messages)}건</span></div>)}</div><p className="text-xs text-muted-foreground">자동 규칙의 1차 분류입니다. 주제 제목은 대표 분류명이며 실제 인용은 원문 영역에서 확인하세요. 대화 수는 고유 사람 수와 다를 수 있고, 한 대화가 여러 주제에 포함될 수 있습니다. 원문 전체는 Data / DM Import에 보존됩니다.</p></div></details>
   </>}
  </>}
 </div>
}
