"use client"
import { useEffect, useState } from "react"
import { ArrowRight } from "lucide-react"
import { intelligenceFetch } from "@/lib/intelligence/client"
import { IntelligenceManagement } from "./management"

type Signal={kind:string;quote:string}
type Evidence={event_key:string;customer_key:string;text:string;quality_kind:string;occurred_at:string;signals?:Signal[];attachment_count?:number}
type Topic={tag:string;title:string;next_action:string;conversations:number;intent_conversations:number;orders:number;examples:Evidence[]}
type Dashboard={summary:{incoming:number;signals:number;conversations:number;media_unread:number};categories:{quality_kind:string;messages:number}[];topics:Topic[];examples:Evidence[];products:{product_key:string;label:string}[];purchase_tracking_connected:boolean}
type Library={total:number;items:Evidence[];media_unread:number;scope_counts:Record<string,number>}
const names:Record<string,string>={problem:'실행·사업 고민',desire:'원하는 변화',objection:'구매·실행 장벽',question:'실제 질문',support:'사용·결제 지원',testimonial:'판매·수익 경험',progress:'실행·완성 경험',feedback:'강의·상품 후기',purchase_report:'구매했다고 언급',unclear:'분류되지 않은 원문',courtesy:'인사·감사',trigger:'키워드 요청',keyword_only:'키워드 요청',no_text:'본문 없음',reaction:'반응',followup:'확인·연락 예고'}
const scopes=[['marketing','고민·질문'],['objection','구매 장벽'],['testimonial','판매·수익 경험'],['progress','실행·완성·후기'],['support','사용 지원'],['all','전체 원문 검색']] as const
const tabs=[['overview','고객 인사이트'],['words','고객 원문 찾기'],['content','콘텐츠 보관함'],['conversion','구매 성과'],['settings','설정']] as const
const btn='inline-flex items-center justify-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-medium hover:bg-muted disabled:opacity-50'
const field='rounded-lg border bg-background p-2 text-sm'
const count=(n:number)=>n.toLocaleString('ko-KR')
export default function IntelligenceOverview(){
 const [tab,setTab]=useState<string>('overview'),[days,setDays]=useState(0),[scope,setScope]=useState('marketing'),[product,setProduct]=useState(''),[revision,setRevision]=useState(0)
 const [data,setData]=useState<Dashboard|null>(null),[library,setLibrary]=useState<Library|null>(null),[loading,setLoading]=useState(true),[finding,setFinding]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false)
 const [topic,setTopic]=useState<string|null>(null),[customer,setCustomer]=useState<{key:string;anchor:string}|null>(null),[format,setFormat]=useState('Content Idea'),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[offset,setOffset]=useState(0)
 useEffect(()=>{let active=true;setLoading(true);setError('')
  intelligenceFetch(`/api/intelligence?days=${days}&scope=${scope}&product=${encodeURIComponent(product)}`).then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)})
  return()=>{active=false}
 },[days,scope,product,revision])
 useEffect(()=>{if(tab!=='words')return;let active=true;setFinding(true);setError('')
  intelligenceFetch(`/api/intelligence?action=library&days=${days}&scope=${scope}&product=${encodeURIComponent(product)}&search=${encodeURIComponent(query)}&offset=${offset}${topic?`&topic=${encodeURIComponent(topic)}`:''}`).then(d=>{if(active)setLibrary(d)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setFinding(false)})
  return()=>{active=false}
 },[tab,days,scope,product,query,offset,topic,revision])
 function chooseScope(value:string){setScope(value);setTopic(null);setOffset(0);setTab('words')}
 async function save(e:Evidence){setBusy(true);setError('');try{await intelligenceFetch('/api/intelligence?action=content',{event_key:e.event_key,format});setStatus(`${format} 소재를 원문과 함께 저장했어요.`)}catch(e){setError(e instanceof Error?e.message:'저장하지 못했어요.')}finally{setBusy(false)}}
 function quote(e:Evidence){const quotes=[...new Set(e.signals?.map(s=>s.quote)||[])];const labels=[...new Set(e.signals?.map(s=>s.kind)||[])];return <article key={e.event_key} className="space-y-4 rounded-2xl border bg-card p-5"><div className="flex flex-wrap justify-between gap-3 text-xs text-muted-foreground"><div className="flex flex-wrap gap-2">{(labels.length?labels:[e.quality_kind]).map(k=><span key={k} className="rounded-full bg-muted px-3 py-1">{names[k]||'고객 원문'}</span>)}</div><time>{new Date(e.occurred_at).toLocaleDateString('ko-KR')}</time></div>{quotes.length?<><p className="text-xs text-muted-foreground">원문에서 찾은 표현 · 고객의 자기 보고</p>{quotes.slice(0,4).map((q,i)=><blockquote key={i} className="max-h-64 overflow-auto whitespace-pre-wrap break-words border-l-2 border-primary/50 pl-4 leading-relaxed">{q}</blockquote>)}<details className="text-sm"><summary className="cursor-pointer text-muted-foreground">이 메시지 전체 보기{quotes.length>4?` · 추가 표현 ${quotes.length-4}개`:''}</summary><p className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap break-words leading-relaxed">{e.text}</p></details></>:<p className="max-h-72 overflow-auto whitespace-pre-wrap break-words">{e.text||'텍스트 없이 보낸 기록입니다.'}</p>}{(e.attachment_count||0)>0&&<p className="rounded-lg bg-muted p-3 text-xs">첨부 {e.attachment_count}개 · 이미지 속 내용은 아직 분석하지 않았어요. 현재 분류는 DM 본문 기준입니다.</p>}<div className="flex flex-wrap gap-2"><button className={btn} onClick={()=>setCustomer({key:e.customer_key,anchor:e.event_key})}>앞뒤 대화 보기</button>{labels.length>0&&<button className={btn} disabled={busy} onClick={()=>void save(e)}>소재로 저장 <ArrowRight className="size-4"/></button>}</div></article>}
 const scopeName=scopes.find(([key])=>key===scope)?.[1]||'고객 문의'
 return <div className="mx-auto max-w-6xl space-y-7 p-4 md:p-8">
  <header className="flex flex-wrap justify-between gap-4"><div><p className="mb-2 text-sm text-muted-foreground">Customer Intelligence</p><h1 className="text-2xl font-semibold md:text-3xl">고객은 무엇을 고민하고, 어떤 변화를 경험했나요?</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-muted-foreground">과거 DM 전체에서 고객 경험·질문·구매 장벽을 찾으세요. 한 메시지에 여러 의미가 있으면 각각 남깁니다.</p></div><button className={btn} disabled={loading||finding} onClick={()=>setRevision(v=>v+1)}>새로고침</button></header>
  <nav aria-label="고객 분석 메뉴" className="flex gap-1 overflow-x-auto border-b">{tabs.map(([key,label])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>{setTab(key);setCustomer(null)}} className={`shrink-0 border-b-2 px-4 py-3 text-sm ${tab===key?'border-primary font-semibold':'border-transparent text-muted-foreground'}`}>{label}</button>)}</nav>
  {error&&<div role="alert" className="rounded-xl border border-destructive/30 p-4 text-sm text-destructive">{error}</div>}{status&&<div role="status" className="rounded-xl bg-muted p-4 text-sm">{status}<button className="ml-3 underline" onClick={()=>{setCustomer(null);setTab('content')}}>보관함 열기</button></div>}
  {customer?<section className="space-y-5"><button className={btn} onClick={()=>setCustomer(null)}>← 고객 분석으로 돌아가기</button><IntelligenceManagement key={customer.key+customer.anchor} mode="journey" initialCustomer={customer.key} initialEventKey={customer.anchor}/></section>:tab==='content'||tab==='conversion'||tab==='settings'?<IntelligenceManagement key={tab} mode={tab}/>:<>
   <div className="flex flex-wrap gap-4"><label className="flex items-center gap-2 text-sm">기간<select className={field} value={days} onChange={e=>{setDays(Number(e.target.value));setOffset(0)}}>{[[0,'전체 기간'],[7,'최근 7일'],[30,'최근 30일'],[90,'최근 90일'],[365,'최근 1년']].map(([n,l])=><option key={n} value={n}>{l}</option>)}</select></label><label className="flex items-center gap-2 text-sm">상품<select className={field} value={product} onChange={e=>{setProduct(e.target.value);setOffset(0)}}><option value="">모든 상품</option>{data?.products.map(p=><option key={p.product_key} value={p.product_key}>{p.label}</option>)}</select></label></div>
   <div aria-label="찾을 고객 데이터" className="flex flex-wrap gap-2">{scopes.map(([key,label])=><button key={key} aria-pressed={scope===key} className={`${btn} ${scope===key?'border-primary bg-primary/5':''}`} onClick={()=>chooseScope(key)}>{label}</button>)}</div>
   {tab==='overview'?loading?<div role="status" className="rounded-2xl bg-muted p-8">고객 원문을 집계하고 있어요…</div>:data&&<>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['testimonial','판매·수익 경험'],['progress','실행·완성 경험'],['feedback','강의·상품 후기'],['objection','구매·실행 장벽']].map(([k,label])=><button key={k} className="space-y-2 rounded-2xl border p-5 text-left hover:bg-muted" onClick={()=>chooseScope(k==='feedback'?'progress':k)}><p className="text-sm">{label}</p><p className="text-3xl font-semibold">{count(data.categories.find(c=>c.quality_kind===k)?.messages||0)}<span className="ml-2 text-sm font-normal">메시지</span></p><p className="text-xs text-muted-foreground">고객이 보낸 원문 확인 →</p></button>)}</section>
    <p className="text-xs leading-relaxed text-muted-foreground">문구로 찾은 후보입니다. 판매·수익 경험은 고객이 말한 결과이며, 실제 결제 검증이나 강의의 효과 증명과 다릅니다. 한 DM이 여러 항목에 포함될 수 있어요.</p>
    <section className="space-y-4"><h2 className="text-xl font-semibold">반복되는 질문과 고민</h2><p className="text-sm text-muted-foreground">대표 질문 → 고객의 표현 → 앞뒤 맥락 순서로 확인하고 FAQ·콘텐츠 소재로 저장하세요.{!data.purchase_tracking_connected&&' 결제 데이터가 연결되기 전에는 전환율을 계산하지 않습니다.'}</p><div className="grid gap-4 lg:grid-cols-3">{data.topics.slice(0,6).map(t=><article key={t.tag} className="flex flex-col gap-4 rounded-2xl border bg-card p-5"><h3 className="text-lg font-semibold">{t.title}</h3><p className="text-sm">관련 대화 {count(t.conversations)}개</p>{t.examples?.[0]&&<blockquote className="line-clamp-5 border-l-2 pl-3 text-sm leading-relaxed">{t.examples[0].signals?.[0]?.quote||t.examples[0].text}</blockquote>}<p className="mt-auto rounded-xl bg-muted p-3 text-sm">활용: {t.next_action}</p><button className={btn} onClick={()=>{setTopic(t.tag);setOffset(0);setTab('words')}}>이 주제 원문 모두 찾기</button></article>)}</div></section>
    <section className="space-y-4"><h2 className="text-xl font-semibold">고객이 실제로 쓴 말</h2><div className="grid gap-4 md:grid-cols-2">{data.examples.slice(0,4).map(quote)}</div></section>
    <p className="rounded-xl bg-muted p-4 text-sm leading-relaxed">첨부가 있는 고객 DM {count(data.summary.media_unread||0)}건은 이미지 속 내용을 아직 분석하지 않았습니다. 성과 스크린샷이 포함될 수 있어 현재 결과가 모든 성과 사례를 뜻하지는 않아요.</p>
   </>:<section className="space-y-5">
    <div><h2 className="text-xl font-semibold">{topic?data?.topics.find(t=>t.tag===topic)?.title||'선택한 주제':scopeName}</h2><p className="mt-2 text-sm text-muted-foreground">전체 기간의 모든 일치 원문을 검색하고 넘겨볼 수 있어요. 앞뒤 대화에는 내가 보낸 답변도 함께 나옵니다.</p>{topic&&<button className={`${btn} mt-3`} onClick={()=>{setTopic(null);setOffset(0)}}>주제 필터 해제</button>}</div>
    <form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();setQuery(search.trim());setOffset(0)}}><label className="sr-only" htmlFor="customer-search">고객 DM 검색</label><input id="customer-search" className={`${field} min-w-52 flex-1`} placeholder="예: 첫 판매, 매출, 초보, 할부, 아이템" value={search} maxLength={200} onChange={e=>setSearch(e.target.value)}/><button className={btn} type="submit">검색</button>{query&&<button className={btn} type="button" onClick={()=>{setSearch('');setQuery('');setOffset(0)}}>검색 초기화</button>}<label className="flex items-center gap-2 text-sm">저장 형식<select className={field} value={format} onChange={e=>setFormat(e.target.value)}>{['Content Idea','Reel','Carousel','Story','FAQ','Sales Page'].map(f=><option key={f}>{f}</option>)}</select></label></form>
    {scope==='all'&&<p className="rounded-xl bg-muted p-4 text-sm">분류에서 빠진 표현도 찾도록 고객 발신 원문을 전부 검색합니다. 인사·반응·본문 없는 기록도 검색 대상이며 인사이트로 집계하지 않습니다.</p>}
    {finding?<p role="status" className="rounded-xl bg-muted p-6">원문을 찾고 있어요…</p>:library&&<><p className="text-sm text-muted-foreground">일치하는 메시지 {count(library.total)}건{library.total>0?` · ${offset+1}–${Math.min(offset+25,library.total)}번째`:''}</p><div className="grid gap-4 md:grid-cols-2">{library.items.map(quote)}</div>{!library.items.length&&<p className="rounded-xl bg-muted p-5">이 조건에 맞는 메시지가 없습니다. 전체 원문 검색으로 바꾸거나 검색어를 줄여보세요.</p>}<div className="flex justify-between gap-3"><button className={btn} disabled={offset===0} onClick={()=>setOffset(n=>Math.max(0,n-25))}>이전 25개</button><button className={btn} disabled={offset+25>=library.total} onClick={()=>setOffset(n=>n+25)}>다음 25개</button></div></>}
   </section>}
  </>}
 </div>
}
